// Example of static member function.....
using namespace std;
#include <iostream>
class StaticMemberFun {
	private:
		int num;        // non-static data member...
		static int cnt; // static data member...
	public:
		void input(int a) { // non-static member function....
			num = a;
			++cnt;
		}
		void display() { // non static member function...
			cout << "Num is :" << num << endl;
		}
		static void display() { // static member function...
			cout << "Count is :" << cnt << endl;
		}
};
int StaticMemberFun::cnt;
int main() {
	StaticMemberFun e1, e2;
	StaticMemberFun::display(); // -> cout is 0...
	e1.input(15);
	e2.input(20);
	StaticMemberFun::displaycnt(); // count is 2....
	e1.display();                  // -> num is 5...
	e2.display();                  // -> num is 20...
	return (0);
}
